"""Deterministic duplicate protection.

One fingerprint per (sport, product, date, content_type, subject, platform).
Two different platforms for the same recap get two different fingerprints
ON PURPOSE — publishing to X must never block publishing the same recap to
Instagram, and vice versa. publish_post() in publishers.py MUST check
already_decided() against the durable history before it calls an adapter.

Example, from the spec: MLB|Moonshot|2026-08-21|HR_RESULT|Ben_Rice|X
"""

from __future__ import annotations

import re

_slug_re = re.compile(r"[^A-Za-z0-9-]+")


def _slug(s: object) -> str:
    s = str(s or "").strip()
    s = _slug_re.sub("_", s).strip("_")
    return s or "NONE"


def fingerprint(*, sport: str, product: str, date: str, content_type: str,
                 subject: str, platform: str) -> str:
    parts = [sport, product, date, content_type, subject, platform]
    return "|".join(_slug(p) for p in parts)


def already_decided(fp: str, known_fingerprints: set[str]) -> bool:
    """True if this exact (post, platform) has already been published or
    explicitly rejected — see store.load_known_fingerprints(). A rejected
    fingerprint stays blocked too: if the fingerprint is regenerated by a
    later run (e.g. a corrected recap), silently re-offering the same
    (subject, platform, date) pair is exactly the accidental-repost the spec
    calls out. The user can always force a genuine repost from the queue UI,
    which mints the post with `repost=True` and bypasses this check on
    purpose."""
    return fp in known_fingerprints
